---
image: voegelas/debian-devel

test:
  script:
    - mkdir build
    - cd build
    - env CFLAGS="-g --coverage -std=c99 -pedantic-errors -Wall -Wextra -Wc++-compat -Wcast-align=strict -Werror" cmake ..
    - make
    - make test
