---
name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: voegelas/debian-devel

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          mkdir build
          cd build
          env CFLAGS="-g --coverage -std=c99 -pedantic-errors -Wall -Wextra -Wc++-compat -Wcast-align=strict -Werror" cmake ..
          make
          make test-coverage
      - name: Report coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
        run: |
          coveralls --file build/lcov.info
